# Generated by Django 3.1.4 on 2022-04-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delta_rn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='probability_gg',
            new_name='score_gg',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='probability_shh',
            new_name='score_shh',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='probability_wnt',
            new_name='score_wnt',
        ),
    ]
