# Generated by Django 3.1.4 on 2021-01-21 16:45

import core_app.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='submit_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='sample',
            name='owner_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('outstanding', 'Outstanding'), ('classified', 'Classified'), ('error', 'Error')], default='outstanding', max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='file',
            field=models.FileField(upload_to=core_app.models.sample_directory_path),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
