# Generated by Django 3.1.4 on 2021-01-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20210121_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='diagnosis',
            field=models.CharField(default='MB', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_identifier',
            field=models.CharField(default='MB2', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='file',
            field=models.FileField(upload_to='data/%Y/%m/%d/'),
        ),
    ]
