# Generated by Django 3.1.4 on 2021-01-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20210121_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='owner_email',
            new_name='email',
        ),
    ]
