# Generated by Django 3.1.4 on 2021-01-21 18:15

import core_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_auto_20210121_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='file',
            field=models.FileField(upload_to=core_app.models.sample_directory_path),
        ),
    ]
