# Generated by Django 3.1.4 on 2021-01-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_auto_20210121_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='medulloblastoma_subgroup',
            field=models.CharField(choices=[('wnt', 'WNT'), ('shh', 'SHH'), ('group 3', 'Group 3'), ('group 3', 'Group 4'), ('nonWNT/nonSHH', 'nonWNT/nonSHH'), ('not classified', 'Not classified')], default='not classified', max_length=20),
        ),
    ]
