# Generated by Django 3.1.4 on 2021-01-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_sample_medulloblastoma_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='medulloblastoma_subgroup',
            field=models.CharField(choices=[('wnt', 'WNT'), ('shh', 'SHH'), ('group 3', 'Group 3'), ('group 3', 'Group 4'), ('non-WNT/non-SHH', 'non-WNT/non-SHH'), ('not classified', 'Not classified')], default='not classified', max_length=20),
        ),
    ]
