# Generated by Django 3.1.4 on 2021-01-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_auto_20210127_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='medulloblastoma_subgroup',
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability_WNT', models.FloatField(null=True)),
                ('probability_SHH', models.FloatField(null=True)),
                ('probability_G3_G4', models.FloatField(null=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app.sample')),
            ],
        ),
    ]
