# Generated by Django 3.1.4 on 2021-02-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_sample_medulloblastoma_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontrol',
            name='sample',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core_app.sample'),
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROX_expired', models.BooleanField()),
                ('FAM_expired', models.BooleanField()),
                ('VIC_expired', models.BooleanField()),
                ('ROX_date', models.CharField(max_length=25)),
                ('FAM_date', models.CharField(max_length=25)),
                ('VIC_date', models.CharField(max_length=25)),
                ('sample', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core_app.sample')),
            ],
        ),
    ]
