# Generated by Django 3.1.4 on 2021-02-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_auto_20210201_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibration',
            old_name='FAM_expired',
            new_name='FAM_valid',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='ROX_expired',
            new_name='ROX_valid',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='VIC_expired',
            new_name='VIC_valid',
        ),
    ]
