# Generated by Django 3.1.4 on 2021-02-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_auto_20210201_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='detected_amplification',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
