# Generated by Django 3.1.4 on 2021-02-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_auto_20210202_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibration',
            old_name='amplification_information',
            new_name='amplification_table',
        ),
    ]
