# Generated by Django 3.1.4 on 2021-02-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_auto_20210208_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='instrument_type',
            field=models.CharField(default='No data', max_length=75),
            preserve_default=False,
        ),
    ]
