# Generated by Django 3.1.4 on 2021-02-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_calibration_instrument_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(choices=[('WNT', 'WNT'), ('SHH', 'SHH'), ('G3', 'G3'), ('G4', 'G4'), ('non-WNT/non-SHH', 'non-WNT/non-SHH'), ('Not classified', 'Not classified')], default='Not classified', max_length=20)),
                ('WNT_probability', models.FloatField(null=True)),
                ('SHH_probability', models.FloatField(null=True)),
                ('G3_G4_probability', models.FloatField(null=True)),
                ('CMS_table', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='medulloblastoma_subgroup',
        ),
        migrations.DeleteModel(
            name='QualityControl',
        ),
        migrations.AddField(
            model_name='classification',
            name='sample',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core_app.sample'),
        ),
    ]
