# Generated by Django 3.1.4 on 2021-02-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_auto_20210208_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='CMS_path',
            field=models.CharField(default='No data', max_length=150),
        ),
        migrations.AlterField(
            model_name='classification',
            name='subgroup',
            field=models.CharField(choices=[('WNT', 'WNT'), ('SHH', 'SHH'), ('non-WNT/non-SHH', 'non-WNT/non-SHH'), ('Not classified', 'Not classified')], default='Not classified', max_length=20),
        ),
    ]
