# Generated by Django 3.1.4 on 2021-02-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0017_auto_20210209_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='CMS_path',
        ),
    ]
