# Generated by Django 3.1.4 on 2021-02-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0018_remove_classification_cms_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='CMS_table',
        ),
    ]
