# Generated by Django 3.1.4 on 2021-02-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_remove_classification_cms_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibration',
            name='amplification_table',
        ),
    ]
