# Generated by Django 3.1.4 on 2021-04-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_remove_calibration_amplification_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='subgroup',
            new_name='subgroup1',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='G3_G4_probability',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='SHH_probability',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='WNT_probability',
        ),
        migrations.AddField(
            model_name='classification',
            name='distLab1',
            field=models.CharField(choices=[('WNT', 'WNT'), ('SHH', 'SHH'), ('non-WNT/non-SHH', 'non-WNT/non-SHH'), ('Not classified', 'Not classified')], default='Not classified', max_length=20),
        ),
        migrations.AddField(
            model_name='classification',
            name='distLab2',
            field=models.CharField(choices=[('WNT', 'WNT'), ('SHH', 'SHH'), ('non-WNT/non-SHH', 'non-WNT/non-SHH'), ('Not classified', 'Not classified')], default='Not classified', max_length=20),
        ),
        migrations.AddField(
            model_name='classification',
            name='score1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classification',
            name='score2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classification',
            name='subgroup2',
            field=models.CharField(choices=[('WNT', 'WNT'), ('SHH', 'SHH'), ('non-WNT/non-SHH', 'non-WNT/non-SHH'), ('Not classified', 'Not classified')], default='Not classified', max_length=20),
        ),
    ]
