# Generated by Django 3.1.4 on 2021-05-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0021_auto_20210426_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='dataframe_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='txt_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('outstanding', 'Outstanding'), ('classified', 'Classified')], default='outstanding', max_length=20),
        ),
    ]
