# Generated by Django 3.1.4 on 2021-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0022_auto_20210504_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('outstanding', 'Outstanding'), ('classified', 'Classified'), ('error1', 'Txt file is incomplete'), ('error2', 'Dataframe is incomplete')], default='outstanding', max_length=20),
        ),
    ]
