# Generated by Django 3.1.4 on 2021-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_auto_20210504_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[(1, 'Outstanding'), (2, 'Classified'), (3, 'Txt file is incomplete'), (4, 'Dataframe is incomplete')], default=1, max_length=20),
        ),
    ]
