# Generated by Django 3.1.4 on 2022-04-20 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid
import workflow.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('sample_identifier', models.CharField(max_length=25)),
                ('diagnosis', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=workflow.models.sample_directory_path)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Classified')], default=0)),
                ('txt_complete', models.BooleanField(default=False)),
                ('all_cpg', models.BooleanField(default=False)),
                ('missing_cpg', models.CharField(blank=True, default='', max_length=25, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(choices=[('WNT', 'WNT'), ('SHH', 'SHH'), ('non-WNT/non-SHH', 'non-WNT/non-SHH'), ('Not classified', 'Not classified')], default='Not classified', max_length=20)),
                ('score_wnt', models.FloatField(default=0)),
                ('score_shh', models.FloatField(default=0)),
                ('score_gg', models.FloatField(default=0)),
                ('sample', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='workflow.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROX_valid', models.BooleanField()),
                ('FAM_valid', models.BooleanField()),
                ('VIC_valid', models.BooleanField()),
                ('ROX_date', models.CharField(max_length=25)),
                ('FAM_date', models.CharField(max_length=25)),
                ('VIC_date', models.CharField(max_length=25)),
                ('amplification_test', models.BooleanField()),
                ('instrument_type', models.CharField(max_length=75)),
                ('sample', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='workflow.sample')),
            ],
        ),
    ]
