# Generated by Django 3.1.4 on 2022-10-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
